### ISSUE TITLE
Meta-issue for improving user-friendliness

### ISSUE THREAD

**Issue by jakobnissen** [RasmussenLab/vamb#240]
Vamb is a somewhat complicated pipeline, which imposes subtle requirements on the inputs for it to work optimally (and sometimes, for it to work at all). While we developers are sensitive to these subtleties, we can't expect our users to be.
Over time, we've had a lot of issues with our users passing bad inputs to Vamb, in which case one of two things happen: In the best case, the program crashes seemingly inexplicably (from the user's PoV), which is a frustrating experience. In the worst case, Vamb just returns bad results without alerting the user.

As a good rule of thumb, if people keep using your program wrong, it's not your users fault for not reading the documentation carefully enough, it's your fault for making the tool too hard to use. I think we now have experience enough with user error to understand how to improve the user friendliness of Vamb. The purpose of this issue is to list common user errors, and to discuss what we can do on the Vamb side to prevent these users errors.

Ideally, we'd do this before Vamb 5 lands, such that we don't need to overhaul and break the API twice.

#### Users are not aware of the version they have installed
Ideally, we should warn users when installing old version of Vamb. However, this is not practically possible.
Instead, we can:

- [x] Make the current version more front-and-center in the README, in the Vamb program itself, in outputs, etc.

#### Users include too small contigs
Vamb doesn't work well with short contigs, both because these contigs have too little signal, and because they recruit reads from the longer contigs, which may distort the abundance estimation.

- [x] Increase the default minimum contig size to 2000
- [x] If smaller contigs are present, warn the user

https://github.com/RasmussenLab/vamb/pull/243

#### Users does not binsplit, or forgets the separator in contigs
User either forgets to pass `-o C`, or they do not quite understand that passing `-o C` imposes restrictions on the naming scheme of your contigs.

- [x] Have two distinct output file: clusters, and split_bins. Only output the latter if a binsplit separator is given.
- [x] Make binsplitting `-o C` the default
- [x] If an explicit separator is given, error if this separator is missing. 
      If the implicit `C` is used, warn the user in log file and stderr, and do not binsplit

#251

#### The user trains on a dataset with too few contigs
The deep learning models in Vamb are, like other DL models, prone to overfitting. Since we have been careful to build the model to usually underfit,
and place high emphasis on model regularization, this problem is not particularly bad for Vamb.
However, with < 50,000 contigs, this might still be an issue.

- [x] Warn users when parsing FASTA files with fewer than 50,000 contigs

https://github.com/RasmussenLab/vamb/pull/244

#### FASTA and BAM headers do not match
One of the most recurrent issues our users have is that they pass in FASTA files and BAM files with differing headers, causing a refhash mismatch.
This can be hard for users to understand.

- [x] Carefully improve the error message on refhash mismatch
- [x] Improve error message when FASTA identifiers are not correctly formatted

#### Users expect high-quality bins, not a complete binning
It's reasonable for users to expect that since the purpose of Vamb is to produce high-quality bins, then the bins generated from Vamb will usually be high quality.
However, this is not the case. Vamb instead outputs ALL contigs as bins, which means the large majority of bins are poor bins, output only so that the result is a complete binning.
The property of outputting a complete, disjoint binning is nice, so we should keep that. However, we also need some way to signal to our users which bins are of higher quality, _without_ making any promises. E.g. having a "good_bins.tsv" file might be a bad idea since Vamb just doesn't have clear-cut information which bins really are good.

Without a dedicated bin quality tool like CheckM, there are a few ways we can estimate bin quality:
* The peak-valley-ratio (PVR) during binning is a reasonable estimation of cluster quality.
  Right now, the observed PVR is not output, only the maximal.
* The bin size MAY be informative, if looking for organisms
* Single-copy genes (SCGs) are informative, but are not yet integrated into the Vamb pipeline.

This is worth thinking about, but I propose:
- [x] Recording the observed PVR of each generated cluster in the `Cluster` object
- [x] Outputting the observed PVR in the clusters output file - or perhaps a separate file?
- [x] Outputting the bin size

#259 

In the future we might also want to output SCG information

**Comment by jakobnissen** [comment]
@sgalkina Let's coordinate on this relative to #204. I can make a series of PRs addressing these UX issues, but they may conflict with #204. If #204 is close to merging, we might as well do that first, then tackle this issue. Else, we'll just deal with the merge conflicts. What's the best approach here you think?

**Comment by sgalkina** [comment]
@jakobnissen I think merging first would be the best. Some UX changes are introduced in https://github.com/RasmussenLab/vamb/pull/204 so better to tackle the high level issues with this new code already 
included
